### PR TITLE
Refine main page design.

### LINKED ISSUE #61: Main Page Advanced Design/Animation
Urgent & Easy
- [x] Add main page name.
- [x] Remove non-useful map-dragging feature.
- [x] Change background image to blank treasure map.

Good to have & Intermediate 
- [ ] Add page transitions.
- [x] Add pop-up side panels including instruction/intro to each mini-app.

### PR DESCRIPTION
**Pull request by fillna**
- Update main page background and map design.
- Complete side panel instruction implementation.
- Remove map draggable functionality.

### CODE REVIEW

**Review by gilkeidar — CHANGES_REQUESTED** [review]
I did encounter two issues and I have one potential idea:

- If you click on a particular continent, that opens its sidebar. But if you click now on a separate continent, nothing happens - you have to click on the continent whose sidebar is currently opened first before you can open the sidebar for a different continent. 
    - My recommendation: You should be able to cycle between continents' sidebars just by clicking on different continents, and when you click on the same continent twice in a row, only then will it close the sidebar.
- Hovering over a continent's text makes the hover go a bit haywire (since the cursor easily moves between hovering over the text or the continent, and only hovering over the continent triggers its on-hover event). Is there a way to make hovering over the text result in the on-hover as well?
- Could we maybe add an image to each continent, e.g. cards for cartomancy, yin-yang symbol for yin-yang-coin, etc? We can use large versions of their favicons

**Comment by fillna** [comment]
Hi Gil, 

Thank you for the recommendation. But based on what we have so far, I think the easiest way to give the user more intuitions of what is being selected is to **highlight the selected location & disable highlight/click on the other ones**. I have made some adjustments to accomplish this, and hopefully it would solve the first issue.

For the second issue, I have made several attempts to solve it yet none of them meet the expectation. Since the continent labels are illustrated using `SVG`, it allocates its own area and makes its **hover effect totally independent from the `.location` class**. The best solution I have for now is to make the labels and the `.location` hover separately, but not all together. **My comment on this is that there is no easy ways to fix it with pure CSS, it would require writing a `hover()` function on the JS file to update the styles.** 

For the continent image, a possible approach would be placing the images with `fixed/absolute` position. It would requires some work to figure out the appropriate coordinates and I am not sure how CSS take care things for different screen size.

If time permits, I will look into the second and third issues more.

**Comment by gilkeidar** [comment]
I think the first issue is the most important tbh, the 2nd and 3rd are optional since they just improve presentation a bit.

I'm still of the opinion that it would be easiest for the user to just click on a different continent and it would open its side bar. The logic for the onclick would probably look something like this:

- If no continent is currently selected, open the sidebar for the continent the user clicked on (already implemented)
- If a continent is currently selected
    - If the continent the user clicked on matches the selected continent, close the sidebar (already implemented)
    - If the continent the user clicked on differs from the selected continent, close the current sidebar + open the sidebar for the new continent

However if this is still an issue, the highlighting could work, but the issue is that it's hard to tell which continent is currently selected. By default, Molybdomancy and Yin Yang Coin are greyed-out, but Cartomancy and Fortune Stick are not, so you can't tell which one is selected. I think this could work if all of the continents are by default the same, laid-back color (e.g. all somewhat grey or something) and when you select one of them it changes color to pop out.

**Comment by IllusiveAldebaran** [comment]
My biggest comment would be exactly the same as Gil's first. Think that is very important and legit I was lost until I figured it out since I checked it blind.

But also want to mention that the popup on the right feels a little smushed, and it would be nice to widen it a bit. Also with changing the zoom a little anything past 133% just starts taking the <ENTER> button out of the screen. 

Looks much nicer to what was there before though. Thanks Jun.

**Comment by fillna** [comment]
Took Gil's idea and updated the continent click effect. It should solve the first issue now.

**Comment by gilkeidar** [comment]
This is great! I agree with Francisco that the background for the slider is a bit "smushed" - is it possible to extend it a bit? 

Besides that, I think this is good to go! Excellent job!!

**Comment by fillna** [comment]
Extend side bar & Finish the polish task.

**Review by gilkeidar — APPROVED** [review]
Looks great! I think we can merge this to `dev` now.

**Pull request merged**
