### PR TITLE
Possible engine implementation

### LINKED ISSUE #5: Sprint 1: Random Answer
- part of the main function for the 8-ball engine
- user should be able to get a random answer that acts as their fortune

### LINKED ISSUE #7: Sprint 1: Answer Dictionaries
- part of the main function of the 8-ball engine
- the app should be able to use different answer dictionaries
- these dictionaries would correspond to various mini-apps based on different fortune telling methods

### PR DESCRIPTION
**Pull request by gilkeidar**
I wrote some prospective engine code based on my understanding of what the backend team needs to do for the first sprint. Please let me know what you think and if this matches the requirements.

Relevant to #5 and possibly also #7

### CODE REVIEW

**Comment by gilkeidar** [comment]
Wait - found extra files that aren't relevant, I'll close this pull request and try again

**Comment by gilkeidar** [comment]
Apologies for the confusion. This pull request is okay - I'll re-open it.

**Review by gilkeidar — COMMENTED** [review]
I think some changes should be made:

- Write comments using JSDocs (i.e. /** */) for automatic documentation
- Rename the `add_outcomes` method to `set_outcomes` (since it doesn't append the input array to the existing outcomes array)
- In the `db_reader` method, what exactly is the bug on line 31?
- Are we using the `outcomes` or `fortune_db` variable to store the list of outcomes in the app? If we want to use a JSON file whose contents are the list of outcomes, then we don't need the `outcomes` array, right?

**Comment by vanvansan** [comment]
I renamed `add_outcome` to `set_outcome`and removed `fortune db`. We will use `this.outcomes` only.

Need to debug on how to get json file loaded before running all the subsequent code.

**Pull request merged**
